### PR TITLE
#30 Bremen more data and source

### PR DESCRIPTION
**Pull request by michaeljokf**
uploaded the extracted CSV files (ERDF 2007-2013, ESF 2007-2013) and
sourced both

### CODE REVIEW

**Comment by cyberbikepunk** [comment]
@michaeljokf this is what happens now when the files don't conform. Just follow the link to details, click on one of the 3 jobs, scroll down the terminal and check out the FAILURES section. It should be fairly clear what's going on. Since all code tests are green, you can assume that if you get a RED, your files are invalid. good luck!

**Comment by michaeljokf** [comment]
@cyberbikepunk okay thanks for the heads up! Its good to know where you are coming from and what you are looking at. I think this should (hopefully) not happen anymore, since I have been using the linter validator but I will make sure and double check!

**Comment by michaeljokf** [comment]
@cyberbikepunk  but the problem was in the source files right? Thats how I understood it. If it was in the CSV files it might have been caused by the transformation (PDF to CSV) process. That would be important to know.

**Comment by cyberbikepunk** [comment]
@michaeljokf I solved this on another branch.

**Pull request closed without merging**
