### PR TITLE
Malta Python scraper

### PR DESCRIPTION
**Pull request by ferblape**
In this PR we are introducing a scraper for Malta.

Notice that I'm not dumping the data to a CSV format, because I don't know to which format. Also, please review the code.

I've also added a new field in the source description

### CODE REVIEW

**Comment by ferblape** [comment]
Ok, I have just added the code to dump the information to a CSV. I haven't committed the CSV, because I'm not sure if you want to have the data in the repository. If so, just tell me.

**Comment by ferblape** [comment]
I have fixed the conflicts with master. This PR is ready and can be reviewed.

**Comment by cyberbikepunk** [comment]
Hey @ferblape sorry it took so long to merge. Thanks a lot for your contribution. I'll let you know if I have any question! Would you be interested in wrangling with data too? Is there something you're particularly interested in?

**Comment by ferblape** [comment]
Hey @cyberbikepunk there's a bug in my script. Line 67 should be `page = 1`. Sorry about that.

This week I'm pretty busy, but if I can help help in anything else, just ping me!

**Comment by cyberbikepunk** [comment]
@ferblape okay thanks for the heads up about the bug.

**Pull request merged**
