### PR TITLE
Feature/111/eu structural funds/bootstrap one pipeline a time

### PR DESCRIPTION
**Pull request by cyberbikepunk**
@akariv @pwalsh This PR adds a command line parameter to the bootstrap module. It solves #111. I thought it was simple but important so that I can work on each pipeline without disturbing the rest. I'm now moving on to #112. Only the [last commit](https://github.com/os-data/eu-structural-funds/pull/116/commits/e661b611e678a29f3651903ced97f1a542eb9794) is different from the #108 PR.

### CODE REVIEW

**Comment by akariv** [comment]
Why are there so many unrelated changes in this pull request?

**Comment by cyberbikepunk** [comment]
@akariv I had to branch off the bootstrap branch (issue 1093). I was also surprised that I was getting all the common commits when I pushed. Is there something I'm missing?

**Comment by akariv** [comment]
This PR shows the diff between the `feature/111/eu-structural-funds/bootstrap-one-pipeline-a-time` branch and the `master` branch. 
If those commits are already in master then there's a problem (usually solved by rebasing). If not, then we should merge the dependency PRs first.

**Comment by cyberbikepunk** [comment]
@akariv I rebased on master, pulled and re-pushed. I'm not quite sure if the diff is now what show at the bottom?

**Comment by akariv** [comment]
I guess that the changes here are not in master yet, so rebasing shouldn't have made a difference.
Let's merge the PRs in which these changes were originally introduced and proceed from there.

**Comment by cyberbikepunk** [comment]
@akariv actually they have been merged and pulled to my local repo.

**Comment by cyberbikepunk** [comment]
@akariv I cherry-picked [0904f18](https://github.com/os-data/eu-structural-funds/pull/116/commits/0904f185170b73d352ed67f0e4fb7d3cfbde9691) made another [PR](0904f18) and merged. I don't know if this very orthodox but I need to move on.

**Pull request closed without merging**
