### PR TITLE
Feature/1093/bootstrap the datapackage pipeline

### PR DESCRIPTION
**Pull request by cyberbikepunk**
I apologize in advance that this PR contains both data and code files. What needs to be reviewed is the [bootstrap.py changes in this commit](https://github.com/os-data/eu-structural-funds/commit/a2da73168c29aa4af5f59986de77993339f87a58).

### CODE REVIEW

**Comment by cyberbikepunk** [comment]
@pwalsh thanks for your review!

**Comment by cyberbikepunk** [comment]
@pwalsh I don't have the experience that you have with contributors using yaml. For me the advantage of yaml files is that they support comments and apparently they've been really useful.

**Comment by cyberbikepunk** [comment]
@pwalsh @akariv Please see the comments in the commit message.

**Comment by cyberbikepunk** [comment]
@pwalsh Are you merging or leaving it to me or waiting for adam to have a look?

**Comment by pwalsh** [comment]
you can merge

**Pull request merged**
