### PR TITLE
Malta 2007-2013 source description

### PR DESCRIPTION
**Pull request by ferblape**
This PR implements part of #72 

Please review and provide feedback @cyberbikepunk and @annafralberts 🚀

### CODE REVIEW

**Comment by cyberbikepunk** [comment]
@ferblape thank you! This looks good to me. Nice website giving lots of info about the projects.

@annafralberts I have a question:

here's an example of 

Focus Area Of Intervention:     OPIIPA2 Continuous training and education.

what official field would we map this to?

**Comment by cyberbikepunk** [comment]
@ferblape can you scrape this?

**Comment by ferblape** [comment]
In Python? I saw @ludo scraper yesterday.

**Comment by cyberbikepunk** [comment]
@ferblape yes we're trying to keep everything to python!

**Comment by cyberbikepunk** [comment]
I'm merging!

**Pull request merged**
